IMDB-BINARY:
  mask_rate: 0.5
  alpha: 0.25
  num_hidden: 512
  num_layers: 2
  lr: 0.00015
  batch_size: 32
  max_epoch: 100
  pooling: mean
  in_drop: 0.2
  attn_drop: 0.1
  num_heads: 2
  lr_f: 0.005
  weight_decay_f: 0
  max_epoch_f: 500
  alpha_l: 1
  residual: False
  scheduler: False
  linear_prob: True
IMDB-MULTI:
  mask_rate: 0.5
  alpha: 0.85
  num_layers: 2
  lr: 0.005
  num_hidden: 512
  batch_size: 32
  max_epoch: 50
  alpha_l: 1
  scheduler: False
  pooling: mean
PROTEINS:
  mask_rate: 0.25
  alpha: 0.5
  num_hidden: 512
  num_layers: 3
  lr: 0.00015
  batch_size: 32
  max_epoch: 150
  max_epoch_f: 0
  pooling: max
  num_heads: 2
  in_drop: 0.2
  attn_drop: 0.1
  alpha_l: 1
  scheduler: False
  linear_prob: True
COLLAB:
  mask_rate: 0.75
  alpha: 0.5
  num_hidden: 256
  num_layers: 2
  lr: 0.00015
  batch_size: 32
  max_epoch: 20
  pooling: max
  in_drop: 0.2
  attn_drop: 0.1
  num_heads: 2
  max_epoch_f: 0
  alpha_l: 1
  activation: relu
  scheduler: True
  linear_prob: True
MUTAG:
  mask_rate: 0.9
  alpha: 0.85
  curMode: geometric
  num_hidden: 32
  num_layers: 5
  lr: 0.0005
  batch_size: 64
  max_epoch: 25
  pooling: sum
  replace_rate: 0.1
  in_drop: 0.2
  attn_drop: 0.1
  num_heads: 2
  max_epoch_f: 0
  alpha_l: 2
  scheduler: False
  linear_prob: True
REDDIT-BINARY:
  mask_rate: 0.75
  alpha: 0.25
  num_hidden: 512
  encoder: gcn
  decoder: gcn
  num_layers: 2
  lr: 0.005
  batch_size: 8
  max_epoch: 150
  pooling: max
  replace_rate: 0.1
  alpha_l: 1
NCI1:
  mask_rate: 0.3
  alpha: 0.25
  curMode: linear
  num_hidden: 512
  num_layers: 3
  lr: 0.005
  batch_size: 16
  max_epoch: 300
  pooling: sum
  alpha_l: 2
  replace_rate: 0.1